### ISSUE TITLE
校内镜像

### ISSUE THREAD

**Issue by volltin** [mbinary/USTC-CS-Courses-Resource#10]
LUGFTP 上对此仓库进行了镜像，LUGFTP 的服务器位于校内机房，校内浏览和下载速度会比较快，另外 FTP/AFP 等协议也方便对目录进行下载等操作。

镜像方式：`git pull https://github.com/mbinary/USTC-CS-Courses-Resource.git -o USTC-CS-Courses-Resource`
更新频率：待定；

支持协议：
- FTP/FTPS:
  - 地址：`ftp.ustclug.org`；
  - 路径：`/ebook/USTC-CS-Courses-Resource`；
  - 用户名：`ftp`；
  - 密码：`ftp`；
- SFTP (Secure File Transfer Protocol):
  - 地址：`ftp.ustclug.org`；
  - 路径：`/ebook/USTC-CS-Courses-Resource`；
  - 用户名：`ftp`；
  - 密码：`ftp`；
- AFP (Apple Filing Protocol)
  - 地址：`afp://ftp.ustclug.org/`；
  - 路径：`/ebook/USTC-CS-Courses-Resource`；
  - Connect As Guest

注意：
- 由于某些原因，不会考虑支持 HTTP/HTTPS 协议；

**Comment by mbinary** [comment]
下载方式已经写在 readme 中了, 感谢:+1:
