### ISSUE TITLE
将作业、实验等内容按照年份划分

### ISSUE THREAD

**Issue by Alexzhoucs** [mbinary/USTC-CS-Courses-Resource#14]
由于不同学期的作业与实验的要求可能存在一些区别，所以在lab目录下建议再按年份划分，方面后面的同学进行查找和添加。

**Comment by mbinary** [comment]
@Alexzhoucs 参考 issue #6

**Comment by mbinary** [comment]
我正在整理, 不过发现大部分课程的作业, 实验, 每年都大同小异. 这种情况直接用最近一年的资料即可

**Comment by Alexzhoucs** [comment]
对于不变的可以直接用一年的，不过考虑到未来可能的变化，是不是在设计上可以预留这样一个可能以供后面的扩展，比如目前的资料是2018的，2019、2020如果不变就仍然使用2018的文件，一旦2021变化了再增加一个文件夹，变为

- lab
-- 2018
-- 2021

**Comment by mbinary** [comment]
嗯, 这样挺好的, 我改一下

**Comment by mbinary** [comment]
部分课程的作业，实验已经采取建议并修改，
