### ISSUE TITLE
README 小问题

### ISSUE THREAD

**Issue by Smart-Hypercube** [mbinary/USTC-CS-Courses-Resource#16]
最底部，mv 应该是不会导致文件重新上传的～毕竟文件虽然是二进制，但只要没变，object hash 就不会变，不会在 git 中产生新对象

**Comment by mbinary** [comment]
嗯嗯, 对, 只要文件内容没变, 数字摘要不变就行, 谢谢:smiley:

**Comment by mbinary** [comment]
已经修改
