### ISSUE TITLE
两个小建议或问题

### ISSUE THREAD

**Issue by vanishcode** [mbinary/USTC-CS-Courses-Resource#17]
1.是否可以考虑去除经管类等于与计算机，写代码无关的文件？
2.是否可以将部分PDF文件换成链接下载的形式来减少体积？我这里clone有些慢而且容易断流，，

**Comment by mbinary** [comment]
1. 其他资源不用去除呀, 因为放着不碍事, 但是有的同学可能选了那课而需要那资源
2. 嗯, 已经删除一些了, 以后大部分pdf 就用网盘链接
