### ISSUE TITLE
添加下载方式 GitZip

### ISSUE THREAD

**Issue by Deardrops** [mbinary/USTC-CS-Courses-Resource#19]
建议在 `readme.md` 中添加新的下载方式 GitZip，将指定目录下所有文件打包下载。方便同学下载。

步骤：
1. 打开 https://kinolien.github.io/gitzip/
2. 在**文本框**中输入要下载的目录的链接

![image](https://user-images.githubusercontent.com/9463871/53299575-0f45b100-3877-11e9-92b9-cc6107e07085.png)

3. 点击**下载**（Download）

> PS. 不需要 `Github API Access Token` 也可以下载

**Comment by mbinary** [comment]
:ok:
