### ISSUE TITLE
网速真好啊

### ISSUE THREAD

**Issue by fengzhao** [mbinary/USTC-CS-Courses-Resource#23]
这么大的文件，都传到github上来了，只能感叹，没有墙的大学网络真好啊

**Comment by mbinary** [comment]
我上传都是用的手机热点...  而且不是一次上传， 渐进的。
 算一百次 commits 的话， 一次大概就 80m。

**Comment by zzh1996** [comment]
哪里没有墙了。。。如果嫌下载速度太慢的话，可以使用 FTP 方式
