### ISSUE TITLE
你们这样公开授权了吗，校长同意了吗？

### ISSUE THREAD

**Issue by AibiTi** [mbinary/USTC-CS-Courses-Resource#25]
你们这样公开授权了吗，校长同意了吗？

**Comment by weaglew** [comment]
你没看readme吗

**Comment by weaglew** [comment]
> 你们这样公开授权了吗，校长同意了吗？

你没看readme吗

**Comment by mbinary** [comment]
@AibiTi 我们目前已经在征询老师的授权，有些老师已经回复。目前仓库里的资料是经过老师授权的，以及正在征询老师授权的。
