### ISSUE TITLE
关于编译原理 H 课程实验上传了答案的问题

### ISSUE THREAD

**Issue by Blealtan** [mbinary/USTC-CS-Courses-Resource#34]
我是编译原理 H 课程 2017 年的助教曹焕琦，这一仓库中的 `c1` 两个实验均由我主要设计构架。
编译原理 H 课程，尤其是实验，资料均在 ![USTC-Compiler](https://github.com/ustc-compiler) 中公开。一方面希望添加引用，另一方面仓库中的代码已经包含了完成实验所需的“填空”实现，请尽快将其从第一个提交删除、rebase 并 force push 以清理干净 history。

我对公开课程资料没有任何意见，事实上这些内容本就是公开可访问的，并且也非常高兴看到一个综合的索引；但和完成的实现一起公开，并且获得了这样高的知名度，已经对这一课程的将来进行造成了影响。当时设计这一实验是希望在接下来的几年间进行沿用、不断完善，出现一个高知名度的公开答案并不利于后续的实验进展。谢谢理解。

**Comment by qiutian00** [comment]
包容，严谨，开放 @Blealtan

**Comment by mbinary** [comment]
非常抱歉！是我审查上的不严。现在已经删除。

**Comment by Ryuurock** [comment]
哎 尾气都没闻到

**Comment by Blealtan** [comment]
删库了挺遗憾的。。我也没想到会这样，但近4500个fork的影响。。

想法和努力是好的，但整理课程资源公开确实需要注意很多事情，还是感谢你的工作。
