### ISSUE TITLE
您好，请问汪芳庭 数理逻辑的课程，第四章有答案吗

### ISSUE THREAD

**Issue by hejianhui** [mbinary/USTC-CS-Courses-Resource#4]
看到数理逻辑课程答案只有1-3章，请问是因为贵校不教第四章所以没有答案吗？还是说学校内部也没有？

**Comment by mbinary** [comment]
嗯， 答案是同学们自己做出来的， 没有与教材配套的答案。 第四章确实不做要求， 只是稍微讲解一下。
